---
# This automation simulates the use of the IKEA TRADFRI Dimmer control
# connected through ZHA.

blueprint:
  source_url: https://github.com/jannikbryld/homeassistant-config/blob/main/blueprints/Tr%C3%A5dfri%20-%202%20button%20cover%20remote.yaml

  name: ZHA - IKEA TRADFRI - 2 Button Open/Close Remote - Custom Actions

  description: >-
    This automation simulates the use of the IKEA TRADFRI open/close switch
    connected through ZHA.

  domain: automation

  input:
    remote:
      name: IKEA TRADFRI remote control
      description: Select the remote control you wish to use.
      selector:
        device:
          filter:
            - integration: zha
              manufacturer: IKEA of Sweden
              model: TRADFRI open/close remote
    up_open:
      name: Short Press - Open Button
      description: The action to perform on Short Press of the Open Button
      selector:
        action:
      default: []
    down_close:
      name: Short Press - Close Button
      description: The action to perform on Short Press of the Close Button
      selector:
        action:
      default: []
    stop_opening:
      name: Long Press - Open Button
      description: The action to perform on Long Press of the Open Button
      selector:
        action:
      default: []
    stop_closing:
      name: Long Press - Close Button
      description: The action to perform on Long Press of the Close Button
      selector:
        action:
      default: []

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - choose:
      # Short-Press the on button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "up_open" }}'
        sequence: !input up_open

      # Long-Press the on button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "stop_opening" }}'
        sequence: !input stop_opening

      # Short-Press the off button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "down_close" }}'
        sequence: !input down_close

      # Long-Press the off button
      - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.command == "stop_closing" }}'
        sequence: !input stop_closing

    # Any other event will cancel the repeat loops (i.e. releasing the [on|off] button)
    default: []